### PR TITLE
Fix sysex and stuff

### PR DESCRIPTION
**Pull request by DixelU**

### CODE REVIEW

**Comment by Kaydax** [comment]
Can you provide example midis where the issue is present?

**Comment by DixelU** [comment]
I'm sorry for the late response.

I sent you the archive with one particular example on your email.

**Comment by Kaydax** [comment]
> I'm sorry for the late response.
> 
> I sent you the archive with one particular example on your email.

Thanks, i'll look into it now

**Comment by Kaydax** [comment]
I assume this fixes the issue, dont feel like getting on windows to test

**Pull request merged**
